* Jarlax
** Description
He created the bragan dearthe. At one time he
lead the entire band of mercenaries, however
over the years he has taken sabbaticals to
Adventure on the surface lands. His power in
the underdark has wavered in  his
absence. He still leads the bragan dearthe in
name but in practice it is segmented into
multiple squads operating  independently of
each other. 

He is one of the only people who can get
materials from the surface surface. So he is
tolerated by the powerful drow houses. The
houses openly praise and accept him. Behindg
closed doors they hate him for his lack of
respect for drow culture. 

Recently the powerful houses have been
attempting to lessen the restrictions put
into place inorder to prevent drows from
going to the surface freely. 

This threatens
the surface as the drow of menzobarenzon are
brainwashed to think surface races are slime
that must be killed.

It also threatens his current position as
broker to the surface.  which for someone
who only lives becase he is irreplaceable
threatens his life. 

he wishes to convertly keep these
restrictions. As he cares for the surface,
and for his own personal power niche in the
underdark.
