

  
* Summary
  One tennat of Menzobarenzon culture was that civilians can
   not freely go to the surface world. The surface world has
  historically been painted as a place of curroption. The
  old ruling houses determined that 
  [[isolationist propoganda strengthens their control over the
  population]]. Opening up the surface would expose the lie. 

  However through the passage of time new leaders have
  suceeded the old leaders, and they believe that the
  [[profits gained from opening the boarders of menzobarenzon]]
  outwiegh the negatives.
  

  Your benifactor, [[Jarlaxe ]]has great political power as
  the leader of one of the only organziations that could
  smuggle goods from the surface the cost.

  His goal is to ensure that drow do not open their boarder
  to the surface. He is willing to attack [[this problem
  through any means necessary]]  
  
 The prision that the pc are inhabiting happens to be a
 private prision under the [[house udan]]. They are a small
 house with a weak military see ([[profits gained from opening
 the boarders of menzobarenzon]]) 
 
* Act 0
** Kassandra 
   She was hired to invistigate missing people, and possibly
   kill or capture a serial killer. She figured out the
   killers next target and camped out their to intercept
   them. Unfortunately the target was high level mage, she
   put kassandra to sleep and brought her back as a prisioner
   to house udan.
** Bellamy
   She got lost in the woods near her monastry and found
   herself caught in the cross fire of a drow raid on an
   isolated dwarven city. They took her back to the underdark
   with the rest of the dwarves, and have been [[Bellamy Torture][torturing]] her
   for months.
** Traedis
   He was hunting darkspawn, and a portal opened up below his feet. He fell
   through and got taken by a drow patrol on the other side.

   
** Act 1
*** Last Time on Dnd
    3 drow prisioners from the Corellon Sisterhood challenge the group to a
    fight. Roki told the party that these sisters run this place, but they
    attack them anyways.
*** Next time
    [[House Udan]] lost their powerful mages in a house struggle. As such
    it is believed they do not have the ability to open a gate
    to the surface world. However, their leader [[Adre'a]] has been
    argueing strongly for opening the gates. [[Jarlaxe]] wishes to
    have the players discover why.
 
** Act 2 
  The players discover that while they do not have mages.
  Another house [[Reizer]] freely gave them a stone that allows
  teleportation to the surface world. Using this stone they
  could without mages invade the surface and pillage openly.
  The players may also learn that behind closed doors they
  have already plundered a dwarf town killing everyone
  except for the towns strongest warrior [[Goiam]]. They took
  him to the prision for study breaking him mentally through
  months of torture.
  
** Act 3
   Upon hearing this news [[Jarlax]] decides he needs time to
   think. He tells the players that no matter what his plan
   is they are going to see combat. He hands them a sack of
   gold for more weapons and magic and tells them to talk to
   his battlemaster [[Jletha]] who will asses the players
   strengths and weaknesses and give them magical gear
   depending on how they do.

** Act 4
   [[Jarlaxe]] reveals that he sees two possible courses of
   action.
*** Course one
    If you guys think you can doit. We destroy [[House Udan]]. 
    They have been severly weakend. You guys as former
    prisioners could insight a riot. Use your connections to
    anger those strong enough to fight against their masters
    whip. When their troups are occupied our mercanaries can
    take action. Of course every member of [[House Udan]] must be
    vanuished. Even though everyone would know that we took
    out [[House Udan]] if it actually gets out that we did it
    would reflect poorly on us.

*** Course two
    It may be enough to simply steal the artifact. [[Reizer]]
    leads a powerful house, and she is not the most
    understanding of woman.  Her resources and experience
    are greater than mine, and I suspect that her
    displeasure would be enough to cause her to take up
    arms.

    No matter what you do retrieve the stone. We have mages that
    can teleport to the surface so I don't need it for
    function. But if it some how ends up in the hands of a great
    house it could be used to create tension among the
    factions who wish to open up the surface...


 in both cases I would like to delegate the planning to you.
 You are domain experts in the ongoings of [[House Udan]]. All
 the Bragan Dearthes resources will be available to you. No
 matter which plan you chose and feel free to come to me
 with any questions you may have about strategy.
 
** Act 5
   Rewards are in order.
*** Aarons characters
      As a suprise for you our mages of finished gathering
     material components require to open up a gate. You may go
     home now if you wish. However I hope you are aware that you do
     have a place in the Bragan Dearthe if you would rather
     stay. I have seen your power. The Dearthe would help
     you grow if you wish to let them.

*** Alex's character
   You are special. As you may have noticed this a little
   boys club. And there are problems too big for our little 
   boy minds at times. I would like you to be the face of
   the Bragan Dearthe. Mine makes people angry. But yours is
   more traditional. I want you to deal with clients who
   will refuse to talk to my other captians. And as such I
   am willing offer you control over your own group of
   fighters. My heart belongs to the surface. And I would
   rather spend my days up there. I only with to deal with
   my duties to the Dearthe when I feel like it is currently
   threatened. So when we finish manipulating the council
   believe it or not I think you have a shot at gaining
   control of the dearthe. Provided you are willing to take
   said shot.

** Act 6

*** If aaron decides to stay 
    I am glad you decided to stay. I would like to use the
    material components to introduce you to the oracle. A
    powerful elven lady from the surface. I believe talking
    to her will strengthen your resolve for are current
    cause. Additionally as a woman sympathetic to our cause
    she will offer you aid in the form of magical artifacts
    tailored to whatever she sees in you. He jiggles one of
    his amulates and becomes translusent for a moment.
*** If aaron decides to leave
   Ill ask aaron where he wants to go and who he wants to
   meet.
   
   At they end of it [[Jarlaxe]] decides whatever happened was
   sweet. But Alex needs a new second in command. And I
   introduce her to Aarons new character.

   There is still much to do. We have stopped one house. There
 are more. For now take some much needed rest.







* test
** tesno
| 1                   | 2                |                    3 |                                 4 |                                                         5 | 6 |
|---------------------+------------------+----------------------+-----------------------------------+-----------------------------------------------------------+---|
| prision escape      | steal drow relic | join bregan daearthe | cut off funding to powerful house | propoganda campain to make house fear teleportation magic |   |
| join bragan dearthe | steal drow relic |                      |                                   |                                                           |   |

* prison 
** Description
You wake up outside.  purple ambient light
reflects off the underdark cieling of a
prision cage in the outskirts of
menzobarenson.

There is a row of cages. In your cage you
see a beaten looking [[Goiam][dwarf]], a calm [[roki][duegar]], a
red  [[mincus][huminnoid lizard]], and a large leathery
skined monster that you recoginize to be a
[[krag][ogre]].

the cage next to you quakes as an equally
large horned bipedal  [[bessy][cow]]  smashes her
horns violently at its bars. 
** Characters 
*** Goiam
**** Description
     A beaten dwarf lays with his back to the bars
     of his cave. He can barely stand. His red
     beard is torn and only covers half his face.
     the other half of his face is a dark mass of
     scabs and ingrown hair. He is gently sobbing.
**** Background
     just there for flavor. he will only cry when
     trapped too.
*** bessy
**** Description
A large minitour agressivly quakes the cage
next to you.  She is currently the only
creature in the cage. but fresh bloodstains
paint the floor beneath her.
**** Background
Normally dark elves dont enaslave
minitouars. they are hard to tame. they are
not trying to tame this lady however. she
will be sent to the arenas wild.  
*** roki
**** Description
bald duegar. He picks his teeth with a quill
from his black spikey beard of quills. He
looks at ease. He has a spiderweb
tattoo on his elbow. It is from before
he was a drow prisioner though.
**** Background
He has also been here for a while he knows
how the system works and fakes being weaker
than he is so he won't be sold. All things
considering he has a good thing going at the
prison. He knows how to get contraband in and
he his friends with the gaurds. people
protect him as long as he's useful and
doesn't stop on anyone's toes.
*** mincus
*** Description
    kobold. Red lizard man. Not beat up. 
**** Background
He used too serve a dragon. But she lost one
of her eggs to a stupid gnome and a goddy
tiefling. She rejected him and her other
servants and he's been having a bad time on
his own. He went to the underdark looking
for a way to redeem himself in her eyes. As
servitude is all he knows.  things considered
he doesn't mind being a slave. As being an
independent thinker served him pretty poorly
thus far. 
*** krag
**** Description
Ogre. He massive with no hair and grey skin.
Chained and scarred. His heard is slightly
caved in. He is in the same cage as you. 
**** Background
he has been here for a while. The drow are
prepping him for the market.They are almost
done breaking his spirit.
** Events
*** Mining 
    a [[female-guard]] and [[male-gaurd]] hand you pick axes. They
    lead you outside the prison. you walk for hours. the
    lights of menzobarenson fade in the distance. One
    directional lamps face away from your path creating a [[barrier of light on path ][
    barrier of light(insight)]]. eventually you come across an
    area filled with shiny ore. the male gaurd points to a
    mining cart and tells you to fill it. Enfebled slaves
    toil on the rocks.

male guard looks at larger player
character.  "alright lets see what you
got. Hit that iron deposit right over
there. No slaves broke  it yet. but ur a
big  boy." 
 [[hit ore][hit ore (athletics)]]

there is a ruby in the ground.
 [[take rubyfrom mine][take ruby (slight of hand)]]


    a monster walks into the camp and just start killing
    folk. Guards don't care. when one of the prisoners die.
    the guy guard gives the female gaurd a few copper.


if the players beat the monster male gaurd
strectches out his hand towards the female
gautd. but she ignores him.


the female gaurd asks where the pcs
learned to fight. she says there is
better work available if the players
answer earnestly.

*** prision riot
[[roki][roki]] mentions "I heard the last
inaffiliated drow prisioner insited a
prison riot."

he doesn't know how they did it as most
slaves here are demoralized. 
 if the players ask. 

"she must have found something that the
prisoners cared more about then their
lives and had them rally behind
that. But i dunno. the drow and a
fewvpeople escaped and everyone else
died. I heard this from a guard and
guards aren't about giving prision
break tutorials."

*** offer to join gang
A gaurd takes the pcs to a heavily
fortified large gated area. There are
bleachers practice dummies, a flat
soccer ball, and a pullup bar.

 [[roki]] immediately plops his ass on the
bleachers. He exchanges roots for dried
pasta.

a  gang  made up of heavily tattoed
drow women.

 [[drow gang tattoos]] . they call
themselves the [[corellon larethian][larethian]] sister hood. 

A large mohawked drow hands Alex a chiv
and says "if you stab that disgusting
lizard you can join us as a box fairy"

"well keep you really safe for your stay
here."

*** gaurd beats a child
    a little drow boy is dressed in what
    looks like guard footie pajamas. hes
    hugging  a male drow leg as the
    drow instructs military men in the art off
    swordplay.

    the instructor has the players to join
    as sparing partners.

He asks "no one hurt each other too
bad."

    A woman wearing a flowey
    white robe walks towards the men. She
    wields a whip with a head of snakes.

    "battle master why isnt terminus
    training", the words fly out of her mouth like
    daggers.

    "watching is training", he says with a coy
    smile. 

    the boy let's  go of the man's
    leg and starts to run.

    the woman responds with the hiss of her
    snake whip. the whips jaw unhinges and
    clasps around the child leg.

    "You must learn to be tough and represent
    house roti properly.", she says. 

    "battle master teach him properly, and
    if your disposition rubs off on him any
    more your skills with the blade will not
    save ur job our your life."  

    she releases her whip an storm's off
    angrily.

the battle master doesn't seem to care
for her comment. He walks up to the
boy. whispers something in the boys ear
and the boy whipes down a tear and limps
away. 

*** Girl gaurds harrass male guard
    She tips water on his croch and
     awkwardly whipes it off. Then
    smacks his ass with the towel and
    says "move along candy ass". 
 
    he looks at her puts on a fake smile
     then turns around frowns and
     beats the crap out of [[Goiam][Goiam]]

    after a while of this. the girl
    starts getting chocked by [[bessy][bessy]]. 

    the man stops beating [[Goiam][Goiam]] to turn and
    help her. [[let her die (persuasion)][let her die]]

if she dies the foreman promotes him.
*** introduce jarlaxe
[[./jarlax.org][a beautifully dressed male drow]]  walks
and starts talking to prisioners. He
sports an impressive amount of
bling. gold chains drape his brightly
colored silk vest. The legs of  his leather
pants are skin colored but patterened in
a way that makes it look like he is
wearing red lingerie. 

He hands one of the guards a sack of
coins and she points to ur cage and
walks away.

He stares at the player characters until
they speak to him. 

"I heard that u were strong and i dont
mean to assume... but judging by your current
prediciment ... im guessing that you are not
a fan of the current establishment. Im
about to piss them off properly. So
perhaps,  in exchange for ur help i could
buy you out of this situation. You would
be mercenaries not slaves."

if they ask why he stared at them.
"Just sizing you up"

Anyways as a retainer her is some gold ontop
of ur freedom. if u want work find my
headquarters and there is some armorments and
information in it for you. 

He unlocks the cell and jingles as he
walks away.


*** house udan investigation intro
**** info to give players
- [ ] [[house udan]] was the house that owned their
  prision.
- [ ] jarlaxe was the anonmous bag of gold. alexs
  char was the only thief crazy enough to try
  stealing from house [[house udan]]
- [ ] [[house udan]] lost all its mages in a recent
  conflict with a destroyed house.
- [ ] the battle master fought with jarlaxe once
  he is a strong opponent, and is uncharistically
  a good man. hes also currently sleeping with the
  matriarch of [[house udan]]. Its best to stay away
  from him, as he can and will kill them.

* Female-guard
* male-gaurd
* barrier of light on path
  +-----+-----+
  |check  |  de   sc   |
  +-----+----------+
  | 10  |These     |
  |     |lights    |
  |     |ward off  |
  |     |the       |
  |     |powerful  |
  |     |wild life |
  |     |of the    |
  |     |underdark.|
  |     |          |
  +-----+----------+
  |     |          |
  |     |          |
  |     |          |
  |     |          |
  |     |          |
  |     |          |
  |     |          |
  |     |          |
  |     |          |
  +-----+----------+

* take rubyfrom mine
|-------+---------------------------|
| check | desc                      |
|-------+---------------------------|
|    15 | You wait until the guards |
|       | are turned away and you   |
|       | slidethe ruby into the    |
|       | lining of ur underwear.   |
|       |                           |
+-------+---------------------------+  

* let her die (persuasion)
  +------+---------------+
  |      |               |
  | check|  desc         |
  |      |               |
  |      |               |
  +------+---------------+
  |  7 - |he smiles      |
  |      |pondering it   |
  |      |for a          |
  |      |moment. then   |
  |      |slowly walks   |
  |      |to help her.   |
  |      |by giving      |
  |      |her the        |
  |      |whip.          |
  +------+---------------+
  |      |               |
  |      |               |
  |  else|               |
  |      |               |
  |      |               |
  |      |               |
  |      |               |
  |      |               |
  |      |               |
  |      |               |
  |      |         he    |
  |      |stabs her in   |
  |      |the back.      |
  |      |eventually     |
  |      |ahigher ranking|
  |      |guard comes in |
  |      |sees the knife |
  |      |inn her back   |
  |      |and promotes   |
  |      |the murderer.  |
  +------+---------------+
* isolationist propoganda strengthens their control over the population
The surface world is painted  as a dangerous place filled
with demons. There great wonders but they are built on top
of lies. The people there want nothing more than to genicide
the drow.
** Why?
*** Not all drow are born with drow culture.
    Some are born with a neutral or even good demeanor, but
    living among drows tends to normalize the evils that they
    witness on a daily basis. Older drows remember a time
    when drows were influenced by surface races, and during
    this time their ability to predict the moves of their
    subjects was weakend.
*** If it aint broke don't fix it
    Some isolationists thoughts are more practical than
    macheavelion. The current rules have worked in their favor,
    and they do not wish to see what happens if they are
    changed.
*** Religous argument
    Lloth has not explicitly been consulted on this subject.
    Those most loyal to her do not wish to risk angering her
    by inadvertantly doing something against her wishes. They
    would however change their minds if they believed this to
    be the will of Lloth.
*** Power vacuum
    If the surface world opened up war would inevitably 
    strike out. Surface lands won during this  war would
    create room for new leaders. New leaders would dillute
    the total power that the old leaders currently have.
*** Some do not believe that the drow as a race would come up on top after a war with the surface 
    Most believe that the drow are superior to every surface
    race in every way, and drow could only be victorious in
    battle. A small subet of others though believe an all out
    war the the surface could mean extinction. The drows
    military might isn't as strong as the propoganda leads
    people to believe. There is alot of internal strife that
    severly weakens the cohesion of drow armies. In war a
    drow soilder is just as likely to get stabbed in his back
    as he is in his front.
* profits gained from opening the boarders of menzobarenzon
** Jarlax would lose alot of power.
   He has power that a man who rejects drow culture has no
   right to have. His ideals threaten the ruling powers.
   Further more his insolent attitude constently angers
   them. The only reason they don't kill him is that he is
   indespensible to menzobarenzon. As one of the only
   consistent conduits to the surface his death would be a
   great blow to menzobarenzon as a whole.
** Low ranking houses see it as a way to gain land.
   Attacking a powerful drow house would be sucide, but a small
   hobbit village not so much. There is not room these
   leaders in menzobarenzon, but the world can be a much
   bigger place if they succefully open it.
** Some just want to piss off the old leaders (Voting on party lines)
   Drow are petty. Some do not care about any potential
   benifits or negatives to this legislation. They are just
   happy to go against the wills of their adverseries. House
   mothers that take this route are suprisingly successful,
   so long as they don't get caught. It wins them favor
   among their alleys and royally fucks their enemies
   schemes.
** One believes that he can rule the world
   As of the begining of the campaign he will keep this
   close to his chest, as any threat to the oligarchy is a
   death warrent for himself. But he is good at operating in
   choas and he beleives the confusion created will let him
   swoop in as a dictator.

* hit ore
  | check | desc                        |
  |     7 | The ore makes the           |
  |       | lightest tink sound. Like a |
  |       | small bell on a kittens     |
  |       | collar jiggling as it       |
  |       | gently breathes mid nap.    |
  |       |                             |
  |    10 | the cracks down the middle  |
  |       | giving a good foothold for  |
  |       | another strike.             |
  |    17 | the ore explodes.           |
  |       |                             |
  |    20 | nothing happens....at       |
  |       | first. You know the rock is |
  |       | broken. It is, just the     |
  |       | rock wont know that is for  |
  |       | 3 more seconds. The guard   |
  |       | leta out a laugh," i        |
  |       | thought u looked tough. but |
  |       | i guess ur another slave."  |

* drow gang tattoos
They have tattoo sleeves on their necks
arms and backs.
- compass with 8 points
- drow woman with ethral spider legs
skulltilla with symbol female gaurds
wear around their necks imprinted in head
- orc/gnome/human wrapped up in a spider
web.
- a naked male drow spread eagle covering
his junk with a greatsword.
* corellon larethian
creator of elves.
* Bellamy Torture
  They are testing out how much punishment surface dwarves
  can take before perishing. Initially they were just going
  to kill her as she is a human and the test was designed
  for dwarves, but when she proved to be hardier than the
  other dwarves she kinda became a pet project to the
  scientists there. There methods involve putting her in a
  pitch black room and beating her until she
  falls unconcious.
