* test
** tesno
| 1                   | 2                     |                    3 | 4 | 5 |
|---------------------+-----------------------+----------------------+---+---|
| prision escape      | steal drow relic      | join bregan daearthe |   |   |
| join bragan dearthe | take down drow family |                      |   |   |


* prison 
** Description
You wake up outside.  purple ambient light
reflects off the underdark cieling of a
prision cage in the outskirts of
menzobarenson.

There is a row of cages. In your cage you
see a beaten looking [[Goiam][dwarf]], a calm [[roki][duegar]], a
red  [[mincus][huminnoid lizard]], and a large leathery
skined monstroaity that you recoginize to be a
[[krag][ogre]].

the cage next to you quakes as an equally
large horned bipedal  [[bessy][cow]]  smashes her
horns violently at its bars. 
** Characters 
*** Goiam
**** Description
A beaten dwarf lays with his back to the bars
of his cave. He can barely stand. His red
beard is torn and only covers half his face.
the other half of his face is a dark mass of
scabs and ingrown hair. He is gently sobbing.
**** Background
just there for flavor. he will only cry when
trapped too.
*** bessy
**** Description
A large minitour agressivly quakes the cage
next to you.  She is currently the only
creature in the cage. but fresh bloodstains
paint the floor beneath her.
**** Background
Normally dark elves dont enaslave
minitouars. they are hard to tame. they are
not trying to tame this lady however. she
will be sent to the arenas wild.  
*** roki
**** Description
bald duegar. He picks his teeth with a quill
from his black spikey beard of quills. He
looks at ease. He has a spiderweb
tattoo on his elbow. It is from before
he was a drow prisioner though.
**** Background
He has also been here for a while he knows
how the system works and fakes being weaker
than he is so he won't be sold. All things
considering he has a good thing going at the
prison. He knows how to get contraband in and
he his friends with the gaurds. people
protect him as long as he's useful and
doesn't stop on anyone's toes.
*** mincus
**** Description
kobold. Red lizard man. Not beat up. 
**** Background
He used too serve a dragon. But she lost one
of her eggs to a stupid gnome and a goddy
tiefling. She rejected him and her other
servants and he's been having a bad time on
his own. He went to the underdark looking
for a way to redeem himself in her eyes. As
servitude is all he knows.  things considered
he doesn't mind being a slave. As being an
independent thinker served him pretty poorly
thus far. 
*** krag
**** Description
Ogre. He massive with no hair and grey skin.
Chained and scarred. His heard is slightly
caved in. He is in the same cage as you. 
**** Background
he has been here for a while. The drow are
prepping him for the market.They are almost
done breaking his spirit.
** Events
*** Mining 
a [[female-guard]] and [[male-gaurd]] hand you pick
axes. They lead you outside the prison. you
walk for hours. the lights of menzobarenson
fade in the distance. One directional lamps
face away from your path creating a [[barrier
of light on path ][ barrier of
light(insight)]].  eventually you come across
an area filled with shiny ore. the male
gaurd points to a mining cart and tells you
to fill it. Enfebled slaves toil on the
rocks. 

male guard looks at larger player
character.  "alright lets see what you
got. Hit that iron deposit right over
there. No slaves broke  it yet. but ur a
big  boy." 
 [[hit ore][hit ore (athletics)]]

there is a ruby in the ground.
 [[take rubyfrom mine][take ruby (slight of hand)]]


a monster walks into the camp and just start
killing folk. Guards don't care. when one of
the prisoners die. the guy guard gives the
female gaurd a few copper.


if the players beat the monster male gaurd
strectches out his hand towards the female
gautd. but she ignores him.


the female gaurd asks where the pcs
learned to fight. she says there is
better work available if the players
answer earnestly.

*** prision riot
[[roki][roki]] mentions "I heard the last
inaffiliated drow prisioner insited a
prison riot."

he doesn't know how they did it as most
slaves here are demoralized. 
 if the players ask. 

"she must have found something that the
prisoners cared more about then their
lives and had them rally behind
that. But i dunno. the drow and a
fewvpeople escaped and everyone else
died. I heard this from a guard and
guards aren't about giving prision
break tutorials."

*** offer to join gang
A gaurd takes the pcs to a heavily
fortified large gated area. There are
bleachers practice dummies, a flat
soccer ball, and a pullup bar.

 [[roki]] immediately plops his ass on the
bleachers. He exchanges roots for dried
pasta.

a  gang  made up of heavily tattoed
drow women.

 [[drow gang tattoos]] . they call
themselves the [[corellon larethian][larethian]] sister hood. 

A large mohawked drow hands Alex a chiv
and says "if you stab that disgusting
lizard you can join us as a box fairy"

"well keep you really safe for your stay
here."

*** gaurd beats a child
a little drow boy is dressed in what
looks like guard footie pajamas. hes
hugging  a male drow leg as the
drow instructs military men in the art off
swordplay.

the instructor has the players to join
as sparing partners.

He asks "no one hurt each other too
bad."

A woman wearing a flowey
white robe walks towards the men. She
wields a whip with a head of snakes.

"battle master why isnt terminus
training", the words fly out of her mouth like
daggers.

"watching is training", he says with a coy
smile. 

the boy let's  go of the man's
leg and starts to run.

the woman responds with the hiss of her
snake whip. the whips jaw unhinges and
clasps around the child leg.

"You must learn to be tough and represent
house roti properly.", she says. 

"battle master teach him properly, and
if your disposition rubs off on him any
more your skills with the blade will not
save ur job our your life."  

she releases her whip an storm's off
angrily.

the battle master doesn't seem to care
for her comment. He walks up to the
boy. whispers something in the boys ear
and the boy whipes down a tear and limps
away. 

*** Girl gaurds harrass male guard
    She tips water on his croch and
     awkwardly whipes it off. Then
    smacks his ass with the towel and
    says "move along candy ass". 
 
    he looks at her puts on a fake smile
     then turns around frowns and
     beats the crap out of [[Goiam][Goiam]]

    after a while of this. the girl
    starts getting chocked by [[bessy][bessy]]. 

the man stops beating [[Goiam][Goiam]] to turn and
help her. [[let her die (persuasion)][let her die]]

if she dies the foreman promotes him.
*** introduce jarlaxe
[[./jarlax.org][a beautifully dressed male drow]]  walks
and starts talking to prisioners. He
sports an impressive amount of
bling. gold chains drape his brightly
colored silk vest. The legs of  his leather
pants are skin colored but patterened in
a way that makes it look like he is
wearing red lingerie. 

He hands one of the guards a sack of
coins and she points to ur cage and
walks away.

He stares at the player characters until
they speak to him. 

"I heard that u were strong and i dont
mean to assume... but judging by your current
prediciment ... im guessing that you are not
a fan of the current establishment. Im
about to piss them off properly. So
perhaps,  in exchange for ur help i could
buy you out of this situation. You would
be mercenaries not slaves."

if they ask why he stared at them.
"Just sizing you up"

Anyways as a retainer her is some gold ontop
of ur freedom. if u want work find my
headquarters and there is some armorments and
information in it for you. 

He unlocks the cell and jingles as he
walks away.



* female-guard
* male-gaurd
* barrier of light on path
  +-----+-----+
 |check  |  de   sc   |
  +-----+----------+
  | 10  |These     |
  |     |lights    |
  |     |ward off  |
  |     |the       |
  |     |powerful  |
  |     |wild life |
  |     |of the    |
  |     |underdark.|
  |     |          |
  +-----+----------+
  |     |          |
  |     |          |
  |     |          |
  |     |          |
  |     |          |
  |     |          |
  |     |          |
  |     |          |
  |     |          |
  +-----+----------+

* take rubyfrom mine
|-------+---------------------------|
| check | desc                      |
|-------+---------------------------|
|    15 | You wait until the guards |
|       | are turned away and you   |
|       | slidethe ruby into the    |
|       | lining of ur underwear.   |
|       |                           |
+-------+---------------------------+  

* let her die (persuasion)
  +------+---------------+
  |      |               |
  | check|  desc         |
  |      |               |
  |      |               |
  +------+---------------+
  |  7 - |he smiles      |
  |      |pondering it   |
  |      |for a          |
  |      |moment. then   |
  |      |slowly walks   |
  |      |to help her.   |
  |      |by giving      |
  |      |her the        |
  |      |whip.          |
  +------+---------------+
  |      |               |
  |      |               |
  |  else|               |
  |      |               |
  |      |               |
  |      |               |
  |      |               |
  |      |               |
  |      |               |
  |      |               |
  |      |         he    |
  |      |stabs her in   |
  |      |the back.      |
  |      |eventually     |
  |      |ahigher ranking|
  |      |guard comes in |
  |      |sees the knife |
  |      |inn her back   |
  |      |and promotes   |
  |      |the murderer.  |
  +------+---------------+

* hit ore
  | check | desc                        |
  |     7 | The ore makes the           |
  |       | lightest tink sound. Like a |
  |       | small bell on a kittens     |
  |       | collar jiggling as it       |
  |       | gently breathes mid nap.    |
  |       |                             |
  |    10 | the cracks down the middle  |
  |       | giving a good foothold for  |
  |       | another strike.             |
  |    17 | the ore explodes.           |
  |       |                             |
  |    20 | nothing happens....at       |
  |       | first. You know the rock is |
  |       | broken. It is, just the     |
  |       | rock wont know that is for  |
  |       | 3 more seconds. The guard   |
  |       | leta out a laugh," i        |
  |       | thought u looked tough. but |
  |       | i guess ur another slave."  |

* drow gang tattoos
They have tattoo sleeves on their necks
arms and backs.
- compass with 8 points
- drow woman with ethral spider legs
skulltilla with symbol female gaurds
wear around their necks imprinted in head
- orc/gnome/human wrapped up in a spider
web.
- a naked male drow spread eagle covering
his junk with a greatsword.
* corellon larethian
creator of elves.
